---
name: Config::Augeas::Validator
version: 0.102
author:
  - 'Raphaël Pinson <raphink@cpan.org>'
abstract: ~
license: lgpl
requires:
  Class::Accessor: 0
  Config::Augeas: 0
  Config::IniFiles: 0
build_requires:
  Test::More: 0
provides:
  Config::Augeas::Validator:
    file: lib/Config/Augeas/Validator.pm
    version: 0.102
generated_by: Module::Build version 0.26
